# Generated by Django 5.0.6 on 2024-06-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomyshow',
            name='show_themes',
            field=models.ManyToManyField(null=True, related_name='astronomy_shows', to='planetarium.showtheme'),
        ),
    ]
