# Generated by Django 5.0.6 on 2024-06-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0005_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('seat', 'row', 'show_session')},
        ),
    ]
