# Generated by Django 5.0.6 on 2024-06-16 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0006_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtheme',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='show_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='planetarium.showsession'),
        ),
    ]
