# Generated by Django 5.0.6 on 2024-06-19 13:08

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0007_alter_showtheme_name_alter_ticket_show_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomyshow',
            name='image',
            field=models.ImageField(null=True, upload_to=planetarium.models.astronomy_show_image_path),
        ),
    ]
