# Generated by Django 5.0.6 on 2024-06-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0008_astronomyshow_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronomyshow',
            name='show_themes',
            field=models.ManyToManyField(blank=True, related_name='astronomy_shows', to='planetarium.showtheme'),
        ),
    ]
